function Indice = importfile1(filename, dataLines, nombre)
%IMPORTFILE1 Import data from a text file
%  PRAC5ALVARO = IMPORTFILE1(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  PRAC5ALVARO = IMPORTFILE1(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  prac5alvaro = importfile1("C:\Users\alejo\Dropbox (UPV SB2CL)\Ale_Yadi_TEAM\Docencia\Mecatronica\Practica\2023\Practica5\prac5_alvaro.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 10-Apr-2024 13:47:58

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Row", "Timestamp", "Ref", "Vel"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
Table = readtable(filename, opts);
Table.Ref = Table.Ref / 100;
Table.Vel = Table.Vel / 100;

plot(Table.Timestamp,[Table.Ref Table.Vel])

Indice = sum((Table.Ref - Table.Vel).^2)./numel(Table.Timestamp);
title([nombre, 'Indice: ', num2str(Indice)]);
end