name: Evaluate Student Submission

on:
  push:
    paths:
      - '**.csv'

jobs:
  grade-student:
    name: Grade Submission
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2.3.1

      - name: Find uploaded CSV file
        id: find_file
        run: |
          FILE=$(find . -name "*.csv" | head -n 1)
          STUDENT_NAME=$(basename "$FILE" .csv | tr '_' ' ')
          echo "file=$FILE" >> "$GITHUB_ENV"
          echo "name=$STUDENT_NAME" >> "$GITHUB_ENV"

      - name: Run MATLAB Assessment
        uses: matlab-actions/run-command@v2
        with:
          command: |
            setenv('CSV_FILE', '${{ env.file }}');
            setenv('STUDENT_NAME', '${{ env.name }}');
            run('Assesment.m');
            run('generate_readme.m');

      - name: Commit changes, ready to push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add results.csv README.md
          git diff-index --quiet HEAD . || git commit -m "Update results for ${{ env.name }}"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: main
          force: true
